import pytest
from treenode import TreeNode
from solution import Solution

solution = Solution()


# @pytest.mark.incremental
class TestGroup:
    @pytest.mark.parametrize(
        "input, target, output",
        [
            (
                [
                    36,
                    13,
                    37,
                    4,
                    20,
                    None,
                    48,
                    1,
                    5,
                    17,
                    33,
                    43,
                    49,
                    0,
                    2,
                    None,
                    9,
                    14,
                    18,
                    22,
                    34,
                    40,
                    46,
                    None,
                    None,
                    None,
                    None,
                    None,
                    3,
                    7,
                    11,
                    None,
                    16,
                    None,
                    19,
                    21,
                    27,
                    None,
                    35,
                    39,
                    42,
                    45,
                    47,
                    None,
                    None,
                    6,
                    8,
                    10,
                    12,
                    15,
                    None,
                    None,
                    None,
                    None,
                    None,
                    26,
                    32,
                    None,
                    None,
                    38,
                    None,
                    41,
                    None,
                    44,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    24,
                    None,
                    28,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    None,
                    23,
                    25,
                    None,
                    29,
                    None,
                    None,
                    None,
                    None,
                    None,
                    31,
                    30,
                ],
                3.142857,
                3,
            ),
            ([4, 2, 5, 1, 3], 3.5, 3),
            ([4, 2, 5, 1, 3], 4.5, 4),
            ([4, 2, 5, 1, 3], 3.714286, 4),
        ],
    )
    def test_closest_value(self, input, target, output):
        print(f"{input =}")
        root = TreeNode()._array_to_tree_node(input)
        assert solution.closestValue(root, target) == output
